In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score


df=pd.read_csv("PerpData - PerpData.csv")
df.head(10)

C:\Users\HP DEMO\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
C:\Users\HP DEMO\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


NAME  PERCENTAGE  BACKLOG  INTERNSHIP  FIRSTROUND  \
0        Apaar Gupta          99        0           3          90   
1      Aastha Khanna          92        0           3          68   
2        Yogita Rana          84        3           2          69   
3               Kush          67        2           2          23   
4      Pulkit Mittal          57        0           2          78   
5     Gaurav Gambhir          85        0           1          86   
6         Shruti Jha          82        0           3          61   
7  Ayush Vishwakarma          47        0           2          32   
8          Divyanshu          62        2           1          56   
9             Ashish          67        1           0          45   

   COMMUNICATIONSKILLLS  Hired  
0                   100      1  
1                    80      1  
2                    80      1  
3                    60      0  
4                    60      0  
5                    80      1  
6                   100      1  
7                    80      0  
8                    60      1  
9                    60      1

In [2]:
X=df[['PERCENTAGE','BACKLOG','INTERNSHIP','FIRSTROUND','COMMUNICATIONSKILLLS']]
y=df[['Hired']]

In [3]:
model=LogisticRegression()
model.fit(X,y)

C:\Users\HP DEMO\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [4]:
# evaluate the model by splitting into train test sets
X_train, X_test, y_train , y_test= train_test_split(X,y,test_size=0.3, random_state=0)
model2=LogisticRegression()
model2.fit(X_train, y_train)

C:\Users\HP DEMO\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [6]:
#predict class tables for the test set

predicted=model.predict(X_test)
print(predicted)

[0 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1 1 0 1
 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 0 0 1
 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 0 0 1]


In [7]:
# generate class probabilities

probs=model2.predict_proba(X_test)
print(probs)

[[ 0.55289595  0.44710405]
 [ 0.32048461  0.67951539]
 [ 0.4742343   0.5257657 ]
 [ 0.08633615  0.91366385]
 [ 0.35364859  0.64635141]
 [ 0.99490683  0.00509317]
 [ 0.2057806   0.7942194 ]
 [ 0.11517826  0.88482174]
 [ 0.15734357  0.84265643]
 [ 0.35481987  0.64518013]
 [ 0.87421035  0.12578965]
 [ 0.02252032  0.97747968]
 [ 0.2457757   0.7542243 ]
 [ 0.24427453  0.75572547]
 [ 0.81390699  0.18609301]
 [ 0.385255    0.614745  ]
 [ 0.03306991  0.96693009]
 [ 0.17793094  0.82206906]
 [ 0.05940275  0.94059725]
 [ 0.09910918  0.90089082]
 [ 0.10812026  0.89187974]
 [ 0.60011303  0.39988697]
 [ 0.20038803  0.79961197]
 [ 0.35678253  0.64321747]
 [ 0.6551843   0.3448157 ]
 [ 0.08262104  0.91737896]
 [ 0.2103775   0.7896225 ]
 [ 0.12857206  0.87142794]
 [ 0.4166465   0.5833535 ]
 [ 0.59287805  0.40712195]
 [ 0.41688862  0.58311138]
 [ 0.48291268  0.51708732]
 [ 0.05553159  0.94446841]
 [ 0.40743457  0.59256543]
 [ 0.02358639  0.97641361]
 [ 0.64641063  0.35358937]
 [ 0.22329995  0.77670005]
 

In [8]:
model.predict_proba(np.array([90,1,3,80,100]).reshape(1,-1))

array([[ 0.09676155,  0.90323845]])

In [9]:
model.predict_proba(np.array([40,4,0,50,60]).reshape(1,-1))

array([[ 0.9770576,  0.0229424]])